-- ProsejurixHub: esquema Usuario / Trámite (Supabase Free)
-- Aplicar en SQL Editor del dashboard o: supabase db push

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- usuarios
-- ---------------------------------------------------------------------------
create table if not exists public.usuarios (
  id bigint generated by default as identity primary key,
  nombre text not null,
  cedula text not null unique,
  telefono text,
  celular text,
  celular_secundario text,
  email text,
  direccion text,
  ciudad text,
  fecha_vinculacion date not null default current_date,
  poderes_firmados boolean not null default true,
  caso_entregado boolean not null default true,
  tiene_vehiculo_involucrado boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists usuarios_cedula_idx on public.usuarios (cedula);

-- ---------------------------------------------------------------------------
-- tramites
-- ---------------------------------------------------------------------------
create table if not exists public.tramites (
  id text primary key,
  usuario_id bigint not null references public.usuarios (id) on delete cascade,
  titulo text not null,
  caso_label text,
  estado_general text not null default 'activo'
    check (estado_general in ('activo', 'en_espera', 'finalizado')),
  etapa_actual text not null default 'accion_penal',
  es_caso_adicional boolean not null default false,
  fecha_accidente date,
  fecha_estructuracion date,
  lugar_accidente text,
  responsabilidad text,
  caducidad date,
  aseguradora text,
  radicado text,
  fiscalia text,
  juzgado text,
  placa_vehiculo text,
  demandado text,
  valor_honorarios numeric,
  valor_peritaje numeric,
  valor_prestamos numeric,
  gastos_adicionales numeric,
  alcance text,
  gestion text,
  observaciones text,
  observaciones_internas text,
  observaciones_cliente text,
  fecha_ingreso date not null default current_date,
  origen_key text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists tramites_usuario_id_idx on public.tramites (usuario_id);
create index if not exists tramites_caducidad_idx on public.tramites (caducidad);
create unique index if not exists tramites_origen_key_uidx
  on public.tramites (origen_key)
  where origen_key is not null;

-- ---------------------------------------------------------------------------
-- etapas (checklist JSONB incluye archivos con url_externa Drive)
-- ---------------------------------------------------------------------------
create table if not exists public.etapas (
  id text primary key,
  tramite_id text not null references public.tramites (id) on delete cascade,
  tipo text not null,
  estado text not null default 'pendiente',
  subestado text,
  fecha_inicio date,
  fecha_fin date,
  notas_internas text,
  notas_cliente text,
  checklist jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tramite_id, tipo)
);

create index if not exists etapas_tramite_id_idx on public.etapas (tramite_id);

-- ---------------------------------------------------------------------------
-- comunicaciones
-- ---------------------------------------------------------------------------
create table if not exists public.comunicaciones (
  id text primary key,
  usuario_id bigint not null references public.usuarios (id) on delete cascade,
  tramite_id text references public.tramites (id) on delete set null,
  tipo text not null,
  direccion text not null,
  fecha timestamptz not null default now(),
  asunto text,
  contenido text not null,
  registrado_por text,
  duracion_minutos integer,
  created_at timestamptz not null default now()
);

create index if not exists comunicaciones_usuario_id_idx on public.comunicaciones (usuario_id);

-- ---------------------------------------------------------------------------
-- agenda_notas
-- ---------------------------------------------------------------------------
create table if not exists public.agenda_notas (
  id text primary key,
  tipo text not null check (tipo in ('recordatorio', 'novedad')),
  fecha date not null,
  titulo text not null,
  detalle text,
  usuario_id bigint references public.usuarios (id) on delete set null,
  tramite_id text references public.tramites (id) on delete set null,
  hecho boolean not null default false,
  creado_por text,
  creado_en timestamptz not null default now()
);

create index if not exists agenda_notas_fecha_idx on public.agenda_notas (fecha);

-- ---------------------------------------------------------------------------
-- profiles (rol admin para RLS)
-- ---------------------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  role text not null default 'admin' check (role in ('admin', 'viewer')),
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------
alter table public.usuarios enable row level security;
alter table public.tramites enable row level security;
alter table public.etapas enable row level security;
alter table public.comunicaciones enable row level security;
alter table public.agenda_notas enable row level security;
alter table public.profiles enable row level security;

-- Fase Free / piloto: lectura y escritura para anon + authenticated
-- (endurecer a solo authenticated admin antes de producción sensible)
drop policy if exists "usuarios_all_anon" on public.usuarios;
drop policy if exists "tramites_all_anon" on public.tramites;
drop policy if exists "etapas_all_anon" on public.etapas;
drop policy if exists "comunicaciones_all_anon" on public.comunicaciones;
drop policy if exists "agenda_notas_all_anon" on public.agenda_notas;
drop policy if exists "profiles_select_own" on public.profiles;

create policy "usuarios_all_anon" on public.usuarios for all using (true) with check (true);
create policy "tramites_all_anon" on public.tramites for all using (true) with check (true);
create policy "etapas_all_anon" on public.etapas for all using (true) with check (true);
create policy "comunicaciones_all_anon" on public.comunicaciones for all using (true) with check (true);
create policy "agenda_notas_all_anon" on public.agenda_notas for all using (true) with check (true);
create policy "profiles_select_own" on public.profiles for select using (auth.uid() = id);

create or replace function public.keepalive_ping()
returns integer
language sql
security definer
as $$
  select 1;
$$;

grant execute on function public.keepalive_ping() to anon, authenticated;
